-- Script para criar as tabelas no Supabase (SQL Editor)

-- Tabela de Contatos (do formulário da index.html)
CREATE TABLE IF NOT EXISTS contatos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    nome TEXT NOT NULL,
    telefone TEXT NOT NULL,
    email TEXT,
    servico TEXT,
    mensagem TEXT
);

-- Tabela de Candidaturas (do formulário trabalhe-conosco.html)
CREATE TABLE IF NOT EXISTS candidaturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    nome_completo TEXT NOT NULL,
    data_nascimento DATE,
    nacionalidade TEXT,
    telemovel TEXT,
    email TEXT,
    morada TEXT,
    distrito TEXT,
    concelho TEXT,
    autorizacao_trabalho TEXT,
    area_inscricao TEXT,
    escolaridade TEXT,
    cursos TEXT,
    certificacoes TEXT,
    experiencia TEXT,
    funcoes TEXT,
    periodo TEXT,
    idiomas TEXT,
    disponibilidade_horarios TEXT,
    competencias_especificas TEXT,
    deslocacoes TEXT,
    jornada_interna TEXT,
    arquivos_nomes TEXT -- Apenas os nomes dos arquivos para referência
);

-- Habilitar RLS (Row Level Security) se desejar,
-- por enquanto as políticas abaixo permitem inserção pública para simplificar o teste inicial.

ALTER TABLE contatos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir inserção pública de contatos" ON contatos FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir leitura apenas autenticada" ON contatos FOR SELECT USING (auth.role() = 'authenticated');

ALTER TABLE candidaturas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir inserção pública de candidaturas" ON candidaturas FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir leitura apenas autenticada" ON candidaturas FOR SELECT USING (auth.role() = 'authenticated');
